const express = require('express');
const fs = require('fs');
const path = require('path');
const { exec } = require("child_process");
const pino = require("pino");
const {
    default: makeWASocket,
    useMultiFileAuthState,
    delay,
    makeCacheableSignalKeyStore,
    Browsers,
    jidNormalizedUser
} = require("@whiskeysockets/baileys");
const { upload } = require('./mega');

let router = express.Router();

// තාවකාලික Folder එක මකාදැමීම
function removeFile(FilePath) {
    if (fs.existsSync(FilePath)) {
        fs.rmSync(FilePath, { recursive: true, force: true });
    }
}

router.get('/', async (req, res) => {
    let num = req.query.number;
    if (!num) return res.status(400).send({ error: "Number is required" });

    // එක් එක් User සඳහා අද්විතීය Session Path එකක් (Render එකේ ගැටළු මගහරවා ගැනීමට)
    const sessionPath = path.join(__dirname, `../temp_session_${Math.random().toString(36).substring(7)}`);
    
    if (!fs.existsSync(sessionPath)) {
        fs.mkdirSync(sessionPath, { recursive: true });
    }

    async function DanuwaPair() {
        const { state, saveCreds } = await useMultiFileAuthState(sessionPath);
        
        try {
            let DanuwaPairWeb = makeWASocket({
                auth: {
                    creds: state.creds,
                    keys: makeCacheableSignalKeyStore(state.keys, pino({ level: "fatal" })),
                },
                printQRInTerminal: false,
                logger: pino({ level: "fatal" }),
                // iOS සහ Android දෙකටම ගැළපෙන Browser Config එක
                browser: Browsers.macOS("Chrome"),
                syncFullHistory: false,
                markOnlineOnConnect: true,
            });

            // Pairing Code එක ලබා ගැනීම
            if (!DanuwaPairWeb.authState.creds.registered) {
                await delay(5000); // සර්වර් එක සූදානම් වීමට කාලය ලබාදීම
                num = num.replace(/[^0-9]/g, '');
                const code = await DanuwaPairWeb.requestPairingCode(num);
                
                if (!res.headersSent) {
                    await res.send({ code });
                }
            }

            DanuwaPairWeb.ev.on('creds.update', saveCreds);

            DanuwaPairWeb.ev.on("connection.update", async (s) => {
                const { connection, lastDisconnect } = s;

                if (connection === "open") {
                    console.log("Login Successful! Processing credentials...");
                    
                    // ⚠️ වැදගත්: Render එකේ creds.json එක හරියටම Save වෙන්න තත්පර 15ක් ඉන්නවා
                    await delay(15000); 

                    try {
                        const credsPath = path.join(sessionPath, 'creds.json');
                        
                        if (fs.existsSync(credsPath)) {
                            // Mega එකට Upload කිරීම
                            const mega_url = await upload(fs.createReadStream(credsPath), `ZANTA_SESSION_${Date.now()}.json`);
                            const string_session = mega_url.replace('https://mega.nz/file/', '');
                            
                            const user_jid = jidNormalizedUser(DanuwaPairWeb.user.id);
                            
                            // User ගේ Inbox එකට Session ID එක යැවීම
                            await DanuwaPairWeb.sendMessage(user_jid, { 
                                text: `*✅ ZANTA-MD CONNECTED SUCCESS*\n\nID: \`${string_session}\`\n\n> *© Generated by Zanta-MD*` 
                            });

                            console.log("Session ID sent successfully!");
                        } else {
                            console.log("Error: creds.json file not found in session path.");
                        }
                    } catch (e) {
                        console.error("Critical Upload Error: ", e);
                    }

                    // ක්‍රියාවලිය අවසන් වූ පසු පිරිසිදු කිරීම
                    await delay(5000);
                    removeFile(sessionPath);
                    process.exit(0); // සර්වර් එක නැවත පණගැන්වීමට (Restart) ඉඩ ලබාදීම
                }

                if (connection === "close") {
                    let reason = lastDisconnect?.error?.output?.statusCode;
                    if (reason !== 401) {
                        console.log("Connection closed, attempting to reconnect...");
                    } else {
                        console.log("Authentication failed. Removing session folder.");
                        removeFile(sessionPath);
                    }
                }
            });

        } catch (err) {
            console.error("Pairing Logic Error: ", err);
            removeFile(sessionPath);
            if (!res.headersSent) {
                res.status(500).send({ code: "Service Unavailable" });
            }
        }
    }

    return await DanuwaPair();
});

module.exports = router;
