const express = require('express');
const fs = require('fs');
const path = require('path');
const { exec } = require("child_process");
const pino = require("pino");
const {
    default: makeWASocket,
    useMultiFileAuthState,
    delay,
    makeCacheableSignalKeyStore,
    Browsers,
    jidNormalizedUser
} = require("@whiskeysockets/baileys");
const { upload } = require('./mega');

let router = express.Router();

// Folder එක මකාදැමීමට (Clean up)
function removeFile(FilePath) {
    if (fs.existsSync(FilePath)) {
        fs.rmSync(FilePath, { recursive: true, force: true });
    }
}

router.get('/', async (req, res) => {
    let num = req.query.number;
    if (!num) return res.status(400).send({ error: "Number is required" });

    // සෑම User කෙනෙකුටම වෙනම Folder එකක් (Render එකේදී Error නොවීමට)
    const sessionPath = path.join(__dirname, `../temp_session_${Math.random().toString(36).substring(7)}`);
    
    if (!fs.existsSync(sessionPath)) {
        fs.mkdirSync(sessionPath, { recursive: true });
    }

    async function DanuwaPair() {
        const { state, saveCreds } = await useMultiFileAuthState(sessionPath);
        
        try {
            let DanuwaPairWeb = makeWASocket({
                auth: {
                    creds: state.creds,
                    keys: makeCacheableSignalKeyStore(state.keys, pino({ level: "fatal" })),
                },
                printQRInTerminal: false,
                logger: pino({ level: "fatal" }),
                // iOS/Android දෙකටම stable වැඩ කරන Browser Config එක
                browser: Browsers.macOS("Chrome"),
                syncFullHistory: false,
                markOnlineOnConnect: true,
            });

            // Pairing Code එක ඉල්ලීම
            if (!DanuwaPairWeb.authState.creds.registered) {
                // සර්වර් එක සූදානම් වීමට තත්පර 5ක් ලබාදීම (iOS Notification සඳහා වැදගත්)
                await delay(5000); 
                num = num.replace(/[^0-9]/g, '');
                const code = await DanuwaPairWeb.requestPairingCode(num);
                
                if (!res.headersSent) {
                    await res.send({ code });
                }
            }

            DanuwaPairWeb.ev.on('creds.update', saveCreds);

            DanuwaPairWeb.ev.on("connection.update", async (s) => {
                const { connection, lastDisconnect } = s;

                if (connection === "open") {
                    console.log("WhatsApp Connection Opened!");
                    await delay(8000); // Creds.json එක සම්පූර්ණයෙන් ලියවෙන්න කාලය ලබාදීම

                    try {
                        const credsPath = path.join(sessionPath, 'creds.json');
                        if (fs.existsSync(credsPath)) {
                            
                            // Mega එකට Upload කිරීම
                            const mega_url = await upload(fs.createReadStream(credsPath), `SESSION_${Math.random().toString(36).substring(7)}.json`);
                            const string_session = mega_url.replace('https://mega.nz/file/', '');
                            
                            const user_jid = jidNormalizedUser(DanuwaPairWeb.user.id);
                            
                            // Session ID එක User ගේ Inbox එකට යැවීම
                            await DanuwaPairWeb.sendMessage(user_jid, { 
                                text: `*ZANTA-MD SESSION ID SUCCESSFUL*\n\nID: \`${string_session}\`\n\n> © Generated by Zanta-MD` 
                            });

                            console.log("Session sent to WhatsApp.");
                        }
                    } catch (e) {
                        console.log("Error uploading session: ", e);
                    }

                    // වැඩේ ඉවර නිසා Folder එක මකා දමා Logout වීම
                    await delay(3000);
                    removeFile(sessionPath);
                    DanuwaPairWeb.end();
                }

                if (connection === "close") {
                    let reason = lastDisconnect?.error?.output?.statusCode;
                    if (reason !== 401) {
                        // Unauthenticated නෙවෙයි නම් නැවත උත්සාහ කරන්න පුළුවන්
                    } else {
                        removeFile(sessionPath);
                    }
                }
            });

        } catch (err) {
            console.log("Pairing Logic Error: ", err);
            removeFile(sessionPath);
            if (!res.headersSent) {
                res.status(500).send({ code: "Service Unavailable" });
            }
        }
    }

    return await DanuwaPair();
});

module.exports = router;
